CREATE TABLE [dbo].[EnrolledClass]
(
    [StudentId] CHAR(7) NOT NULL PRIMARY KEY,
    [ClassId] CHAR(4) NOT NULL PRIMARY KEY,

    CONSTRAINT [FK_EnrolledClass_Class] FOREIGN KEY ([ClassId]) REFERENCES [Class]([ClassId]) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT [FK_EnrolledClass_Student] FOREIGN KEY ([StudentId]) REFERENCES [Student]([MaHocSinh]) ON DELETE CASCADE ON UPDATE CASCADE,
)
